### ISSUE TITLE
redundant data in extracted files (PC2)

### ISSUE THREAD

**Issue by MikeVapour** [Nenkai/PCarsTools#1]
Hello!
Firstly, thanks very much for the tool!
I tested it with PC2 on PC and extracted some bff's using the quickbms+cheat engine+renamer method and your tool. The files extracted with your tool have extra data added at the end and they cause game crashes.
I attach several examples (the files ending in CA have beet extracted with quickbms and renamed via cheat engine)
https://www.mediafire.com/folder/lhidwh4fv9q0r/PC2_files
I can provide more samples if needed.
Is it something you can address?

**Comment by Nenkai** [comment]
Retest with [1.0.1](https://forum.xentax.com/viewtopic.php?f=16&t=23276&p=188252#p188252)

**Comment by MikeVapour** [comment]
Fantastic! It works as advertised.
Thank you kindly!
