### ISSUE TITLE
Can't unpak Test Drive Ferrari Legends bff file

### ISSUE THREAD

**Issue by Thunderflash81** [Nenkai/PCarsTools#10]
Hello I try to unpak Test Drive Ferrari Legends bff file but i've always error message
Any solutions ?

pcarstools_x86.exe pak -i "Z:\PCarsTools.exe112\publish\x32\f333sp.bff" -g "Z:\PCarsTools.exe112\publish\x32" --game-type "TDFRL"

**Comment by Nenkai** [comment]
Try with 1.1.4.
Please provide the error message if it still happens.
