### ISSUE TITLE
Some Project Cars 1's Tracks BFFs cannot be extracted.

### ISSUE THREAD

**Issue by TBNRassault0030** [Nenkai/PCarsTools#12]
![image](https://github.com/Nenkai/PCarsTools/assets/86336214/76a2bdcb-1a94-48e6-b408-b990acebc3e5)

Some Track BFFs cannot extracted, usually, half of the BFFs having "GP" on their name.

**Comment by Nenkai** [comment]
Try with 1.1.4.
