### ISSUE TITLE
Support for .meb version 0.7.0.0 (Fast and Furious Crossroads, Project CARS 3)

### ISSUE THREAD

**Issue by oxmaulmike2581** [Nenkai/PCarsTools#2]
Hi!
First of all, thanks for that project, you are genius. Really.

Can you please add the support for version 0.7.0.0 of .meb files (which used in such games like Fast and Furious Crossroads, Project CARS 3)?

The main difference in the header.
In earlier versions header size was 8 bytes, in that version its size is 12 bytes.
I attach an example of .meb file to research.
[acura_nsx_01_body_loda_md.zip](https://github.com/Nenkai/PCarsTools/files/9994835/acura_nsx_01_body_loda_md.zip)

P.S.: (maybe I should create another PR for that, don't know) Fast and Furious Crossroads from PS4 have another .meb format, if you're interested - let me know. I have some (but not all) information about it.

Regards, Mike.

**Comment by Nenkai** [comment]
Addressed in 6d9dbd474552b9b986ae1586ef2e645dc803a886
