### ISSUE TITLE
Model decryption bug

### ISSUE THREAD

**Issue by oxmaulmike2581** [Nenkai/PCarsTools#4]
Hi again.
I found a bug which prevent model importing after decrypting.

In encrypted .mebs, postions have format 0x14 (according to your code, it's DXGI_FORMAT_D32_FLOAT_S8X24_UINT).
Non-encrypted .mebs have format 0x2 (DXGI_FORMAT_R32G32B32A32_FLOAT).

After successful decrypting, format value does not change.
All .meb importers can work only with format 0x2.

Yes, of course, it can be manually fixed by hex editor, but if you have whole car (or even worse, the whole game) unpacked, it will take a time.

Screenshots of what I mean (both files are decrypted by your tool, tested on Automobilista 2):

![image](https://user-images.githubusercontent.com/28642811/201491489-ac69769b-4722-40b5-ba1c-2f9d1f33e885.png)

![image](https://user-images.githubusercontent.com/28642811/201491500-da188559-789d-41a9-a56e-ec651a6d787b.png)

Sorry if I annoy you, I just want to improve that project.

[EDIT][UPD] Seems to be I've found what flags are used in binary mesh header and what other bytes are mean, and my variant is different than your one. Let me know if you're interested in that.

**Comment by Nenkai** [comment]
a20508557a55524038dc5983d87e8b8156bd20e1

Please retest (among other issues) with 1.0.2

**Comment by oxmaulmike2581** [comment]
@Nenkai it works fine, thank you very much. Tested on FF:CR.

About other things that I've said before: I will make another combined issue for all future issues from me (to prevent making a trash can here), okay?
