### ISSUE TITLE
Possible backwards compatibilty of sgb64 PC3 to PC2/AMS2?

### ISSUE THREAD

**Issue by MikeVapour** [Nenkai/PCarsTools#5]
Hello!
It's not an issue, but  a feature request:
I've been trying to convert PC3 tracks to PC2/AMS2.
I narrowed down the main problem to the sgb64 files. AMS2 doesn't load sgb64 from PC3. Swapping sgb64 PC3 for an equivalent PC2 sgb64 track causes many meshes to load.
Is making pc3 sgb64 compatible with the previous games something you would consider looking into?

I attach heusden sgb64 from both pc3 and pc2.

[heusden.zip](https://github.com/Nenkai/PCarsTools/files/10007538/heusden.zip)

**Comment by cyber-speed** [comment]
@MikeVapour 
What are you using to import in to a 3D editor a full vehicle/track, or to convert from MEB to other format?
Or i am assuming thats a secret/private script/tool/etc?
Now that @Nenkai released the most import part of the process, extraction with names plus decryption, i am confused as to what people are using?

**Comment by MikeVapour** [comment]
I use the old Zmodeler to edit mebs.
Tbh, I never convert mebs into a different format as I am only interested in making mods for AMS2.

**Comment by oxmaulmike2581** [comment]
Also will be great if binary template for SGB / SGB64 will be created. I tried to research that format, but it's still unfinished and can't be read properly.

**Comment by MrUnzO** [comment]
> 

can you give some advice to edit some cars on AMS2 I can't edit meb file.

**Comment by Nenkai** [comment]
Out of the scope of this tool. Closing as unlikely to implement anything within the tool itself, however it does not mean that I may not give a quick look at the format.
