### ISSUE TITLE
Support for Test Drive Ferrari Racing Legends

### ISSUE THREAD

**Issue by oxmaulmike2581** [Nenkai/PCarsTools#6]
Hi!

Can you add support for Test Drive Ferrari Racing Legends game? It's 2012 year game on that engine, and the first to introduce encryption, which was later used in Project CARS, etc.

I tried to do that by myself, but failed in testing stage.

I build an archive for you with useful files, it have:
- Game executable (2 versions, cracked (not by me) and original)
- Languages\Languages.bml
- build.dat
- whole "TOCFiles" folder
- one vehicle in "Pakfiles\Vehicles" folder
- Extracted encryption key used to decrypt languages.bml file
- Extracted encryption keys used to decrypt .bff archives

All keys are extracted from game executable and not decrypted, but I think your tool will decrypt them easily.

Unfortunately, I can't find the .pdb files for these .exe.

The archive:
[TDFRL_files.zip](https://github.com/Nenkai/PCarsTools/files/10047978/TDFRL_files.zip)

Regards, Mike.

**Comment by Nenkai** [comment]
https://github.com/Nenkai/PCarsTools/commit/c31c668974392f6479d8021bc240ea07cc4bd584
