### ISSUE TITLE
Model decryption don't work

### ISSUE THREAD

**Issue by Thunderflash81** [Nenkai/PCarsTools#7]
Hi, i try to decrypt model (.meb) from Pcars 2 and AMS2, and it don't work. I've the message "access denied to folder". 
Any ideas ?
Thanks

**Comment by oxmaulmike2581** [comment]
Try to run as administrator. Make sure that no other programs is handling these files (I mean, if the .meb file is opened in Notepad or hex editor, close it before running that tool).
Maybe Microsoft Defender is blocking that tool.

Because I tested the decryption on meshes from AMS2 and it works great.

**Comment by Thunderflash81** [comment]
Thanks, can you confirm to me the command line please?
I try a lot of thing and nothing works, run console at administrator, change MEB files folder, try v1.01 and v1.02 of pcartools. unpack works great, but uncrypt is ko 🤔

**Comment by oxmaulmike2581** [comment]
@Thunderflash81 
1. Remember a path where PCarsTools.exe is located _(or just right-mouse-click on PCarsTools.exe and select "Copy as path")_.
2. Open Command Prompt or Terminal _(I recommend in Command Prompt mode, not PowerShell)_ inside the folder where .meb files are located.
3. Ctrl+V to paste the path to PCarsTools.exe, then type: `decryptmodel -i model_name.meb`
My example: `"C:\PCarsTools\PCarsTools.exe" decryptmodel -i arc_cam_body_cpit.meb`
And press Enter. Now the .meb file should be decrypted.
If you're see a message _"POSITION stream format is not DXGI_FORMAT_D32_FLOAT_S8X24_UINT, model vertices are not encrypted."_, this means that the model is not encrypted.
Repeat this for every .meb file.
I re-tested the decryption again and it works. I used PCarsTools 1.0.2, tested on Windows 11.

**Comment by Thunderflash81** [comment]
Thanks a lot man i'll test it tomorow 👍

**Comment by Thunderflash81** [comment]
Hello, thanks it works !!!
