### ISSUE TITLE
errors unpacking with 1.1.0

### ISSUE THREAD

**Issue by MikeVapour** [Nenkai/PCarsTools#8]
Hi!
I'm getting errors when unpacking with 1.1.0, while everything is fine with the release 1.0.2. Unpacking the same bff from PC2. The errors reported in 1.1.0 (again, 1.0.2 unpacks the same bff correctly, with no errors):

`PCarsTools 1.1.0 by Nenkai#9075

Warning - possible crash: Ferrari_458_SA toc could most likely not be decrypted correctly using key No.4
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_wiper_mask.dds (target=2FC61EF99AA152A3, got=3508957336770840461
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_wiper_trails.dds (target=69C7B46C361707C2, got=9957274547041200138
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_windows_2.bmt (target=BC36DBBFA020C83C, got=6264734617141537368
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_windows.bmt (target=816986518E54D734, got=1381632440764550448
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_paint_plastic.bmt (target=5C36B2752D39B944, got=17620548282315139102
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_paint.bmt (target=AD498FC5FA0333C0, got=2892289445218010697
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_body_loda.meb (target=26F5FF7F6A3434C3, got=8826828922244103157
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_body_loda_dmg.meb (target=68AE21F87B1FF5D2, got=6509304127054451135
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_body_lodb.meb (target=459FC9D0494E1EB2, got=15183094374961529705
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_body_lodb_dmg.meb (target=D458FD7DAED40548, got=4221389086925107090
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_body_lodc.meb (target=C08ACD8E1C33F7AA, got=16899559581641930011
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_body_lodc_dmg.meb (target=ABF3CEF638C46B14, got=15811010293903628645
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_misc_nmp8888.dds (target=9E8170647E23075D, got=1750080439895834700
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_misc_spec.dds (target=788D344EA123D7E5, got=5730967300313794737
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_misc_diff.dds (target=089991EE58C478F1, got=11988389963997300475
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_misc.bmt (target=D6384431A0769641, got=2279733104742988295
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_badges_nmp8888.dds (target=61D18DE99ACD0290, got=14368558971012506691
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_badges_spec.dds (target=691C11CAEF5B3A63, got=13962579316217545954
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_badges_diff.dds (target=0DF7FF276BA5D981, got=4396888359154191490
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_badges.bmt (target=134731DA7B6EEBE1, got=7252697132208676221
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bonnet_loda.meb (target=03E8F6E3591ED9CC, got=17392853322438265786
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bonnet_loda_dmg.meb (target=208642C9A607909D, got=16961752617287772705
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bonnet_lodb.meb (target=8CF9D0128F8B0F76, got=4592372956092135876
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bonnet_lodb_dmg.meb (target=004988A8AF7E3E3B, got=9524718366726849033
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bonnet_lodc.meb (target=5D04C9B15E763BBE, got=16413829844078760616
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bonnet_lodc_dmg.meb (target=D55091ABA7A3286B, got=2017768728043049721
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_f_loda.meb (target=CF300B7138B2504C, got=3822546291479740561
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_f_loda_dmg.meb (target=437EE598BE126864, got=16243196613746838818
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_f_lodb.meb (target=5F6C37FDFF973691, got=4866036611529700830
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_f_lodb_dmg.meb (target=4D77134FBA4E2F07, got=16822474599860010624
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_f_lodc.meb (target=D04AA57D3616BB31, got=12090050884554376788
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_f_lodc_dmg.meb (target=80AABF17ABD8517E, got=11420504719301115645
Warning - unmatched UID/Hash: vehicles\textures\generic_licplate_euro_glow.dds (target=91E9DC8003CFA64B, got=16945957745124649646
Warning - unmatched UID/Hash: vehicles\textures\generic_licplate_euro_nmp8888.dds (target=180DCDB808D6E0C3, got=9202325653565218777
Warning - unmatched UID/Hash: vehicles\textures\generic_licplate_euro_diff.dds (target=E74EA4EB6BCDF7CC, got=1085506290182754392
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_licplate.bmt (target=E3F15E49BCC105E7, got=16911990449476188871
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_carbon_ext1.bmt (target=9F4E14C53878C996, got=2589140289093884544
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_lights_glow.dds (target=D307ADCC1EFC648D, got=14580940032999785007
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_lights_spec.dds (target=0001476FDFB71735, got=6134910463879207234
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_lights_diff.dds (target=AD02FF29C5CCEC48, got=12378302542273157406
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_lights.bmt (target=172A45B19D186E3B, got=6381118635247061222
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_r_loda.meb (target=8C0E9E161F3C10B0, got=12377950719254992647
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_r_loda_dmg.meb (target=25D76F66449B725F, got=5852803954059924416
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_r_lodb.meb (target=B289A0E7F8D7DEB9, got=14883903136035453197
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_r_lodb_dmg.meb (target=AC931F8DABC20704, got=10674480077290229879
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_r_lodc.meb (target=FD6A1E0B1E79DFE8, got=2346738820505011268
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_bumper_r_lodc_dmg.meb (target=82AF6761E11BB607, got=971999372174721960
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_caliper_lf_loda.meb (target=0B50A625F16A8C92, got=13458687337745015231
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_caliper_lf_lodb.meb (target=F19A2136062451E9, got=11878319458036548033
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_caliper_lr_loda.meb (target=05DC14AD0799FDEB, got=15150984196537414062
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_caliper_lr_lodb.meb (target=C0F09B27916F6D2F, got=11062359893874966863
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_caliper_rf_loda.meb (target=B1E40008C351E900, got=4651931993546884135
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_caliper_rf_lodb.meb (target=ECC7E24FD695FEAE, got=9511575270774770097
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_caliper_rr_loda.meb (target=4C59266F81607E7B, got=14400145737366504356
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_caliper_rr_lodb.meb (target=3448DED78C837FE7, got=16875822693683411906
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_badges_2.bmt (target=A517009ACDE76501, got=8530007950290360921
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_chassis_loda.meb (target=E6A46E0B0D52832A, got=13210070194881243597
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_chassis_loda_dmg.meb (target=9168D4CADF218A65, got=7648989034005325338
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_chassis_lodb.meb (target=9AB7F765BFBB8DE5, got=11162788911475822875
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_chassis_lodb_dmg.meb (target=2D0CAFD75F9F0417, got=14455461879714127931
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_chassis_lodc.meb (target=12C8A3944E0C2F44, got=10382536369117962595
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_chassis_lodc_dmg.meb (target=5DD83F5F52ACD1E7, got=15425540065759039311
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_chassis_lodd.meb (target=1BE5E91808228D8F, got=17033383189754562889
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_disc_blur_spec.dds (target=AC29B2AFDB0E1B09, got=9688350122882730183
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_disc_blur_diff.dds (target=FBDA2B30746689C1, got=8288352042593743685
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_disc_spec.dds (target=70D36CAC9D09EB72, got=5371681029103261478
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_disc_diff.dds (target=2D1523F0F8D432D5, got=5769194951373404641
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_disc.bmt (target=1AAC73D1A3C11281, got=5288133072038905403
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_disc_lf_loda.meb (target=FEFA42A113DBD7BC, got=707488850513280371
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_disc_lf_lodb.meb (target=015115EED2975939, got=1452675534637880613
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_disc_lr_loda.meb (target=FFEBA4E580DCE4B1, got=7578578411099446869
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_disc_lr_lodb.meb (target=F829F7702B798B38, got=2955266041972078117
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_disc_rf_loda.meb (target=FABE433F8FD80068, got=15238237082496730742
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_disc_rf_lodb.meb (target=FA4A187F88AEC6AA, got=4145497026339539405
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_disc_rr_loda.meb (target=181DFDAFDDBF84AA, got=14363289718378928096
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_disc_rr_lodb.meb (target=134D5ACAEBF1196C, got=10600306509348310108
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_interior_glow.dds (target=B37F7650D04AEC94, got=18043944935482596883
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_interior_nmp8888.dds (target=2F374C37642D956A, got=2306792085694781432
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_interior_spec.dds (target=A557BE382178324B, got=14111751892572509280
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_interior_diff.dds (target=9D86DA1146ED2557, got=9023886451769759961
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_interior.bmt (target=DD845C6EADC80912, got=7192056439497754755
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_interior_loda.meb (target=54D396F4394D9F52, got=4220594140636732307
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_interior_loda_dmg.meb (target=1F060D8209DE7F1B, got=1045483337775384720
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_interior_lodb.meb (target=93BC4836C06DB116, got=7653573042025346425
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_interior_lodb_dmg.meb (target=823CE7F3DC4FAB79, got=10535984428359293404
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\generic_lightflares.bmt (target=CE1761BEB06164C6, got=17833608822824071086
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_lightglows_f_loda.meb (target=90DF12281D5F5EEC, got=18327933696803673981
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_lightglows_r_loda.meb (target=D862A0E2908D5852, got=17927389329807683589
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_lightglass_nmp8888.dds (target=CA4FEF46E9240546, got=17220451697411641059
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_lightglass_spec.dds (target=EF9C566D33184DC6, got=466851813188913717
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_lightglass_diff.dds (target=A6FA28FE819B9102, got=3606750476060956168
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_lightglass.bmt (target=145B0EC2CE7E2231, got=14427726904550900394
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_lights_loda.meb (target=1E626078029264DD, got=15345196016527193255
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_lights_loda_dmg.meb (target=CA5179EF0D7A675D, got=1547135976673802293
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_lights_lodb.meb (target=AFC79DFF7FD07836, got=16514871571816500067
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_lights_lodb_dmg.meb (target=0BAB8498DB1AE104, got=10837501898862643432
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_shadow_loda.meb (target=CF5139CC80E1377D, got=6391947841065883010
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_shadow_loda_dmg.meb (target=8AAA25343DA5BE92, got=18106024383972553989
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_shadow_lodb.meb (target=8328AB67BC0B534C, got=9446001921895743205
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_shadow_lodb_dmg.meb (target=6DE5010021B7CB94, got=4965556908755036758
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_steeringwheel_loda.meb (target=16EE22063F8B9AD1, got=4373814816868913330
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_steeringwheel_lodb.meb (target=9C58737B64F6E6BB, got=589589262152226279
Warning - unmatched UID/Hash: vehicles\textures\tread_michelin_cup2_blur_diff.dds (target=D2B1D59A10A848F0, got=15746749522497887346
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tread.bmt (target=DA093437AECD1168, got=16592564724600533017
Warning - unmatched UID/Hash: vehicles\textures\tire_michelin_cup2_blur_spec.dds (target=AFC57703E08546CB, got=10109595290561376456
Warning - unmatched UID/Hash: vehicles\textures\tire_michelin_cup2_blur_diff.dds (target=62C62ADB03FAE875, got=2286478366354402142
Warning - unmatched UID/Hash: vehicles\textures\tire_michelin_cup2_nmp8888.dds (target=CCCAF07AF2FF8997, got=8614735650982672550
Warning - unmatched UID/Hash: vehicles\textures\tire_michelin_cup2_spec.dds (target=79722AD7D75DD68B, got=9228904548386388328
Warning - unmatched UID/Hash: vehicles\textures\tire_michelin_cup2_diff.dds (target=E136A76D8F065F49, got=3276302105551112121
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire.bmt (target=7078661B1803DB6B, got=5854714012358860413
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_lf_loda.meb (target=0916953B1321C1E8, got=15177264312702038061
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_lf_lodb.meb (target=A22BED73C0F697C2, got=16220748009118154805
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_lf_lodc.meb (target=63848B9B19D05870, got=4771137804048057463
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_lr_loda.meb (target=1A0CDE87DFFEC2FC, got=14052036926987058249
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_lr_lodb.meb (target=DBC8E267ACCC4FB1, got=15773609680986186646
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_lr_lodc.meb (target=657AE674453D0477, got=800691058981854491
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_rf_loda.meb (target=56A42A2EFBA9FD78, got=13699085932860473648
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_rf_lodb.meb (target=8717D981DE4CCA21, got=9375744087200533418
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_rf_lodc.meb (target=1F0FE62C2C9E1C6A, got=16202617836414327119
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_rr_loda.meb (target=C1F7C8ECC3C566DC, got=11594520087862372082
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_rr_lodb.meb (target=0EBA98D9B3F27A21, got=16470903149469803365
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_tire_rr_lodc.meb (target=C4DFB9719A82874F, got=18411292149727137796
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_wheel_blur_spec.dds (target=42BFC4A176E8DE50, got=14815189383838070929
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_wheel_blur_diff.dds (target=B78CC17C2C1E95B5, got=10966054925762122658
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_wheel_nmp8888.dds (target=B7D3B25B3E08121F, got=6669436738062354188
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_wheel_spec.dds (target=2C65F8920B126163, got=7202356155831807950
Warning - unmatched UID/Hash: vehicles\textures\fer_458sa_wheel_diff.dds (target=481912C927E9E103, got=5866849694341223826
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_rim_blur.bmt (target=A38576A974106ADA, got=13174901242893858645
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_rim.bmt (target=E11FFCF72B2F722D, got=4577244533686343153
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_lf_blur_loda.meb (target=5EF0CA2AECC8BD1F, got=3596594981416091860
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_lf_loda.meb (target=A93B44F4FF561DED, got=8543082920329410846
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_lf_lodb.meb (target=545B6E8E9D4A04D0, got=10568797507007378235
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_lodc.bmt (target=19A14484742B8A88, got=13608641370447995007
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_lf_lodc.meb (target=45C86EBD7B2DCF28, got=11876976418383107816
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_lr_blur_loda.meb (target=9227D1A7550E6FC4, got=1709397106802381509
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_lr_loda.meb (target=90C63D085A9AA73B, got=1369871279826779914
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_lr_lodb.meb (target=B7D5232D44540FF1, got=6008790728455074202
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_lr_lodc.meb (target=CFC79670746E156E, got=7483721915807876362
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_rf_blur_loda.meb (target=9B43F87D6A41950D, got=10257036721692655001
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_rf_loda.meb (target=9E2460B9A9A022F2, got=9617342928964094544
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_rf_lodb.meb (target=43FB22F58CECDC00, got=11660610543903970748
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_rf_lodc.meb (target=2C5813C5E6D297D3, got=1931034416684360117
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_rr_blur_loda.meb (target=5833373AB930BB93, got=14038955185170272519
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_rr_loda.meb (target=E332CA819E1A7CB9, got=6668379233373383028
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_rr_lodb.meb (target=2629FCC72A3622E7, got=8241741731882330606
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wheel_rr_lodc.meb (target=E67952F16F95F44D, got=1788140831970588012
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_misc_skin.bmt (target=4EF20853D4459136, got=12899560643190159806
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wiper_loda.meb (target=8900069DC20E16B3, got=6082668205431355141
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\fer_458sa_wiper_lodb.meb (target=1926853697F7A991, got=11866747298403122054
Warning - unmatched UID/Hash: animation\driver\driver.bas (target=6247629A744A0249, got=16678389754799679656
Warning - unmatched UID/Hash: animation\driver\ferrari_458_sa\ferrari_458_sa.bab (target=4B473476DC18279F, got=9671976615959944719
Warning - unmatched UID/Hash: vehicles\_data\headlights.prl (target=6720B5AE51395997, got=16393272545917221530
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\anims\ferrari_458_sa_chassis.bas (target=3B6FA44826326C53, got=15863773443512422815
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\anims\vehicleanims.bab (target=89A886BC78F36AA8, got=15888912006087131041
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\ferrari_458_sa.csdbin (target=3FE0F650A9AE37E3, got=13763242799031276218
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\ferrari_458_sa.vhf (target=82FDADA78747253D, got=12091450802393769265
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\ferrari_458_sa_kt.txt (target=1E4FD6ABAF9AE0EA, got=12961681498551411045
Warning - unmatched UID/Hash: vehicles\physics\chassis\ferrari_458_sa.cdfbin (target=A6CF14D5AB7A148C, got=202798733614994925
Warning - unmatched UID/Hash: vehicles\physics\engines\ferrari_458_sa.edfbin (target=1B5B993E2B829A4A, got=8669062169257506517
Warning - unmatched UID/Hash: vehicles\physics\gearbox\ferrari_458_sa.gdfbin (target=980B50ACF244F511, got=1129619311639715741
Warning - unmatched UID/Hash: vehicles\physics\suspension\ferrari_458_sa.sdfbin (target=F8E9DF5DC14AD0AD, got=15247200601420464206
Warning - unmatched UID/Hash: vehicles\physics\collision\ferrari_458_sa.joi.xml (target=3893BC4A620F216F, got=12421791663490926381
Warning - unmatched UID/Hash: vehicles\physics\collision\ferrari_458_sa.sys.xml (target=1A191E3D3596EDE0, got=6202136342381392919
Warning - unmatched UID/Hash: vehicles\physics\collision\ferrari_458_sa.xml (target=024BE53A53D25340, got=6010010128301783500
Warning - unmatched UID/Hash: vehicles\_data\headlights.dds (target=9CE25501E4302C23, got=2438770551769940108
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\ferrari_458_sa_ambsh.dds (target=FFAE058DCFF749FD, got=683364250921715495
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\ferrari_458_sa.vhf.bml (target=351A0F3414BD291D, got=5590631451558736318
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\ferrari_458_sa.rcf (target=E4055212FE99E3D5, got=6219346050863958311
Warning - unmatched UID/Hash: vehicles\ferrari_458_sa\ferrari_458_sa_hr.rcf (target=A93DD2AD7359D826, got=2213397468184238414
Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'value')
   at System.IO.FileStream.set_Position(Int64 value)
   at PCarsTools.BPakFile.UnpackFromStream(BPakFileTocEntry entry, BExtendedFileInfoEntry extEntry, String output) in C:\Users\nenkai\source\repos\PCarsTools\PCarsTools\BPakFile.cs:line 266
   at PCarsTools.BPakFile.UnpackAll(String outputDir) in C:\Users\nenkai\source\repos\PCarsTools\PCarsTools\BPakFile.cs:line 217
   at PCarsTools.Program.Pak(PakVerbs options) in C:\Users\nenkai\source\repos\PCarsTools\PCarsTools\Program.cs:line 126
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at PCarsTools.Program.Main(String[] args) in C:\Users\nenkai\source\repos\PCarsTools\PCarsTools\Program.cs:line 26`

**Comment by macleod** [comment]
For me, version 1.1.0 says that the library hostfxr.dll was found, but loading it failed. Version 1.0.2 works well.

**Comment by oxmaulmike2581** [comment]
@MikeVapour 
How you are launching that tool? Version 1.1.0 has a new argument (see Readme file for more details).

@macleod 
Seems to be your .NET version is not compatible with application's target platform. Do you have both x64 and x86 versions installed?

**Comment by MikeVapour** [comment]
The new arguments are only for PC1 and Ferrari if I read it correctly. So no change from the old versions when unpacking PCC2 BFFs.

**Comment by macleod** [comment]
> If you mean NET runtime, I installed x64 version 6.0.11, and pct 1.0.2 works well. Should I install the x86 version too?

**Comment by oxmaulmike2581** [comment]
@macleod 
yes

**Comment by macleod** [comment]
OK, I'll try it tomorrow. I'm out for the weeekend.

**Comment by oxmaulmike2581** [comment]
> Warning - possible crash: Ferrari_458_SA toc could most likely not be decrypted correctly using key No.4

@Nenkai 
I have noticed that in some cases the index of the decryption key required for the archive is different from the index recorded in Languages.bml, which causes this problem. I saw this warning when I tested your utility on FF:CR, AMS2, TD:FRL. For example, one of the car archives in TD:FRL was actually encrypted using key №11, not №4 as it should be. It's easy to find out - just take the nfsshift.bms script for QuickBMS and add the key index output there. I saw in your code the part responsible for iterating over the key index, but in this case it does not work, so I have a question: is it possible to do an automatic enumeration of all available keys from all keysets, if the key selected based on the data from Languages .bml doesn't fit? For myself, I just rebuild your project from the sources, manually writing down the index I need, but, as you understand, this method is not suitable for everyone.
I also noticed that for new games the keyset for PC1 is still used by default in some cases (this happened yesterday when trying to unpack some archives from FF:CR).

**Comment by macleod** [comment]
Installing both runtimes s for x86 and x64 solved the issue with unpacking PC1 files, which now works well, but now I have the same issue as @MikeVapour with PC2 files. Version 1.0.2 still works perfectly for PC2.

**Comment by macleod** [comment]
the version 1.1.2 works well with TDFRL, PC1, PC2, PC3, F&F and AMS2

**Comment by Nenkai** [comment]
Thanks for the report!
